services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_USER: go
      MYSQL_PASSWORD: go_bookstore_mgmt
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: bookstore
    ports:
      - "3306:3306"
      - "33060:33060"
